copied code from trials
PowerLevel9000/review-project pull request #1
Opened 2022-12-05 14:49 UTC by PowerLevel9000

i had copied this code from free code camp certification project

2022-12-05 15:02 UTC, PowerLevel9000 commented on styles.css
> +
add header element salector and have width of 100% make your webpage nav bar should be displayed on your whole screen

2022-12-05 15:04 UTC, PowerLevel9000 commented on index.html
> +    </header>
for best practice have class not id

2022-12-05 15:34 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @PowerLevel9000, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of the GitHub review features. 💯 
✅ Your project is documented professionally. 📜 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] **[OPTIONAL]:** It would be great if you use emojis in your review comments! They make the code review more human-friendly 👽🤖.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 15:34 UTC, anagudelogu commented on index.html
> +    </header>
Great job using GitHub inline comments feature! 💯 However, there is room to improve your reviews:

- [ ] Please consider rephrasing your comment to sound more polite as a suggestion instead of an order.

💡 
> This is a polite suggestion: *"I think it would be better to use semantic tags"*
> This reads as an order: *"Use semantic tags"*


- [ ] Please consider providing a better explanation of "why" you're requesting this change, saying that is for `"best practice"` is too vague of a reason.

💡 
> This is a well-explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
> This request lacks a "why": *Why don't you use an article tag here instead of a div?*

Please consider editing this comment and applying the suggestions! 🤓 🛠️

2022-12-05 15:34 UTC, anagudelogu commented on index.html
> +    <main id="main">
- [ ] Please apply the same here, rephrase this comment to sound polite as a suggestion, and also provide an explanation on why changing all ids to class names would improve the codebase! 🤓 🛠️

2022-12-05 15:34 UTC, anagudelogu commented on styles.css
> +
- [ ] Please apply, once again, the same here, rephrase this comment to sound polite as a suggestion, and also provide an explanation on why adding a header element selector and having a width of 100% would improve the codebase, also, please consider being more clear! 🤓 🛠️ 

💡 
> This is a clear comment: *The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?*
> This is a vague comment: *The README is not descriptive, why don't you make it better?*

2022-12-06 01:48 UTC, PowerLevel9000 commented on index.html
> +    </header>
[optional}] let's talk about this  and it would be better if you do the same in the rest of your code

📃kindly, it would be better if you make priorities in class selectors and id selector and have have a definite sequence
      of applying it (class, required attributes, id values) by doing this way you will always know where is the container 
     with that selector is  🧑‍🏫
📃 also it would be better if the document flow and your selectors in the same sequence ✅✔️because if you 
      have any problem in  document flow you will know where to make changes

2022-12-06 02:08 UTC, PowerLevel9000 reviewed
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi! i am Adarsh aka @PowerLevel9000, 



While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

![ClappingLeonardoDicaprioGIF](https://user-images.githubusercontent.com/116451144/205790670-44ff52ce-a4af-468a-bb38-a82aa8a38a41.gif)


## Highlights
✅ Great use of git flow 
✅ meaningful commits 
✔️ your project look good while there is some room of improvement


## Required Changes ♻️
📃 document your project in readme.md file
_Check the comments under the review._

## Optional suggestions

- [ ] **[OPTIONAL]:** It would be great if you use emojis in your review comments! They make the code review more human-friendly 👽🤖.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 02:15 UTC, Tadesse-Alemayehu commented
### Hi @PowerLevel9000 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![gabriel_Igla](https://user-images.githubusercontent.com/69077061/205779485-f4702b3a-8d5c-44b2-9ba5-7050a4f971da.gif)


## Highlights
- [ ]  phrased the comments politely ✔
- [ ]  includes an explanation, a "why", for each requested change. ✔
- [ ]  comments are clear and easy to understand. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 02:16 UTC, Tadesse-Alemayehu approved these changes
### Hi @PowerLevel9000 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![gabriel_Igla](https://user-images.githubusercontent.com/69077061/205779485-f4702b3a-8d5c-44b2-9ba5-7050a4f971da.gif)


## Highlights
- [ ]  phrased the comments politely ✔
- [ ]  includes an explanation, a "why", for each requested change. ✔
- [ ]  comments are clear and easy to understand. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-06 13:39 UTC, closed without merging